version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    container_name: bank-java-app
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_NAME=postgres
      - POSTGRES_DB_PASSWORD=test1234
      - SPRING_PROFILES_ACTIVE=local
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bank-network

  db:
    build:
      context: docker/db
      dockerfile: Dockerfile
    container_name: bank-postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bank-network

  test:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    container_name: bank-java-test
    command: ["./gradlew", "test"]
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB_NAME=postgres
      - POSTGRES_DB_PASSWORD=test1234
      - SPRING_PROFILES_ACTIVE=test
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bank-network

networks:
  bank-network:
    driver: bridge

volumes:
  postgres_data:
